version: '3'

services:
  db:
    container_name: mysql
    image: mysql:8.0.21
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - web-net

  app:
    container_name: backend
    restart: always
    build: ./backend
    ports:
      - "3001:3001"
    environment:
        APP_PORT: 3001
        DB_PORT: 3306
        DB_USER: root
        DB_PASSWORD: password
        DB_HOST: 127.0.0.1
        JWT_SECRET: senhasuperhipermegasecreta
    depends_on:
      - db
    volumes:
      - './:/usr/src/backend'
    networks:
      - web-net
    
    # app2:
    #     container_name: frontend
    #     restart: always
    #     build: ./frontend
    #     ports:
    #         - "3000:3000"

networks:
  web-net:
    name: web-net